apiVersion: v1
kind: PersistentVolume
metadata:
  name: mps-certs
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/mnt/data/mpscerts"